apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/use-regex: 'true'
  name: ingress-nginx
  namespace: {{ .Release.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.HELPER_FQDN }}
    http:
      paths:
      - backend:
          service:
            name: genshin-helper-service
            port:
              number: 443
        path: /genshin/*
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.HELPER_FQDN }}
    secretName: tls-secret