apiVersion: v1
data:
  LINE_CHANNEL_ACCESS_TOKEN: {{ .Values.LINE_CHANNEL_ACCESS_TOKEN | b64enc }}
  LINE_CHANNEL_SECRET: {{ .Values.LINE_CHANNEL_SECRET | b64enc }}
  REDIS_URL: {{ .Values.REDIS_URL | b64enc }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | b64enc }}
  TOKEN: {{ .Values.TOKEN | b64enc }}
kind: Secret
metadata:
  name: genshin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
data:
  tls.crt: {{ .Values.TLS_SIDECAR_CRT | b64enc }}
  tls.key: {{ .Values.TLS_SIDECAR_KEY | b64enc }}
kind: Secret
metadata:
  name: tls-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls