apiVersion: v1
kind: Service
metadata:
  name: genshin-helper-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
      app: genshin-helper 
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP